FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt ./
RUN pip install -r requirements.txt

RUN apt-get update && apt-get install -y libgl1 libglib2.0-0

COPY . .

EXPOSE 5000

CMD ["python", "app.py"]