# docker build -t my_onnx_app .   
# docker run --rm -it -v ./data:/workspace/data my_onnx_app

FROM kneron/toolchain:latest

WORKDIR /workspace

COPY requirements.txt ./
RUN /workspace/miniconda/envs/onnx1.13/bin/pip install -r requirements.txt
RUN apt-get update && apt-get install -y libgl1 libglib2.0-0

COPY opt_onnx.py onnx_tnpu.py constant.py ./
COPY run.sh ./
COPY test.jpg ./

RUN chmod +x run.sh

CMD ["./run.sh"]